apiVersion: planetscale.com/v2
kind: EtcdLockserver
metadata:
  name: vt-etcd-central
  namespace: voip
---
kind: ServiceExport
apiVersion: net.gke.io/v1
metadata:
  namespace: voip
  name: vt-etcd-central-client