apiVersion: v1
kind: Secret
metadata:
  name: db-users
  namespace: voip
type: Opaque
stringData:
  db-users.json: |
    {
      "vitess":[
        {
          "UserData":"vitess",
          "Password":"password"
        }
      ]
    }

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-vitess-url
  namespace: voip
type: Opaque
stringData:
  connectionString: mysql://vitess:password@vtgate:3306/vitess
